// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NnhStudentManager.Data;

#nullable disable

namespace NnhStudentManager.Migrations
{
    [DbContext(typeof(NnhStudentManagerContext))]
    partial class NnhStudentManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NnhStudentManager.Models.NnhMark", b =>
                {
                    b.Property<int>("NnhSubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectId");

                    b.Property<int>("NnhStudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentId");

                    b.Property<float>("NnhScore")
                        .HasColumnType("real")
                        .HasColumnName("Score");

                    b.HasKey("NnhSubjectId", "NnhStudentId");

                    b.HasIndex("NnhStudentId");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("NnhStudentManager.Models.NnhStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NnhClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassId");

                    b.Property<string>("NnhStudentAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("StudentAddress");

                    b.Property<string>("NnhStudentAvatar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("StudentAvatar");

                    b.Property<DateTime>("NnhStudentBirthday")
                        .HasColumnType("date")
                        .HasColumnName("StudentBirthday");

                    b.Property<string>("NnhStudentEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("StudentEmail");

                    b.Property<string>("NnhStudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("StudentName");

                    b.Property<string>("NnhStudentPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("StudentPhone");

                    b.HasKey("Id");

                    b.HasIndex("NnhClassId");

                    b.HasIndex("NnhStudentEmail")
                        .IsUnique();

                    b.HasIndex("NnhStudentPhone")
                        .IsUnique();

                    b.ToTable("Student");
                });

            modelBuilder.Entity("NnhStudentManager.Models.NnhStudentClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NnhClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ClassName");

                    b.HasKey("Id");

                    b.ToTable("StudentClass");
                });

            modelBuilder.Entity("NnhStudentManager.Models.NnhSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NnhSubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SubjectName");

                    b.HasKey("Id");

                    b.HasIndex("NnhSubjectName")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("NnhStudentManager.Models.NnhMark", b =>
                {
                    b.HasOne("NnhStudentManager.Models.NnhStudent", "NnhStudent")
                        .WithMany("NnhMarks")
                        .HasForeignKey("NnhStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NnhStudentManager.Models.NnhSubject", "NnhSubject")
                        .WithMany("NnhMarks")
                        .HasForeignKey("NnhSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NnhStudent");

                    b.Navigation("NnhSubject");
                });

            modelBuilder.Entity("NnhStudentManager.Models.NnhStudent", b =>
                {
                    b.HasOne("NnhStudentManager.Models.NnhStudentClass", "NnhStudentClass")
                        .WithMany("NnhStudents")
                        .HasForeignKey("NnhClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NnhStudentClass");
                });

            modelBuilder.Entity("NnhStudentManager.Models.NnhStudent", b =>
                {
                    b.Navigation("NnhMarks");
                });

            modelBuilder.Entity("NnhStudentManager.Models.NnhStudentClass", b =>
                {
                    b.Navigation("NnhStudents");
                });

            modelBuilder.Entity("NnhStudentManager.Models.NnhSubject", b =>
                {
                    b.Navigation("NnhMarks");
                });
#pragma warning restore 612, 618
        }
    }
}
